name: "build darwin binaries for 'upcheck'"
# This workflow is triggered on pushes to the repository.
on: [push]
env:
  DEVELOPER_DIR: /Applications/Xcode_10.3.app/Contents/Developer
  MACOSX_DEPLOYMENT_TARGET: 10.14

jobs:
  test-darwin:
    name: pytest on darwin
    runs-on: macos-latest
    steps:
      - name: Set up Python 3.7.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
      - uses: actions/checkout@v2
      - run: pip install --extra-index-url https://pkgs.frkl.io/frkl/dev -e '.[testing,all]'
      - name: Test with pytest
        run: pytest tests

  mypy-darwin:
    name: mypy check on darwin
    runs-on: macos-latest
    steps:
      - name: Set up Python 3.7.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
      - uses: actions/checkout@v2
      - run: pip install --extra-index-url https://pkgs.frkl.io/frkl/dev -e '.[testing,all]'
      - name: Test with mypy
        run: mypy src

  flake8-darwin:
    name: flake8 on darwin
    runs-on: macos-latest
    steps:
      - name: Set up Python 3.7.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
      - uses: actions/checkout@v2
      - run: pip install --extra-index-url https://pkgs.frkl.io/frkl/dev -e '.[testing,all]'
      - name: Test with flake8
        run: flake8 src/upcheck

  build-darwin:
    name: build darwin binary
    runs-on: macos-latest
    needs:
      - test-darwin
      - mypy-darwin
      - flake8-darwin
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.pyenv/
          key: ${{ runner.os }}-target-darwin-10.11-upcheck-python-build
      - run: brew install pyenv
      - run: brew install pyenv-virtualenv
      - uses: actions/checkout@v2
      - name: build_binary
        run: ./scripts/build-binary/build.sh --spec-file scripts/build-binary/onefile.spec
#      # uncomment to sign binary (needs certificate data in env)
#      - name: Add MacOS certs
#        run: chmod +x ./scripts/build-binary/add-osx-cert.sh && ./scripts/build-binary/add-osx-cert.sh
#        env:
#          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
#          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
#      - name: sign binary
#        run: "codesign -f -s 'Developer ID Application: Markus Binsteiner (4Q559SZWTL)' dist/darwin19/upcheck"
      - name: Archive Mac OS X binary
        uses: actions/upload-artifact@v1
        with:
          name: upcheck
          path: dist/darwin19/upcheck
